[build]
  command = "npm install && npm run build"
  publish = "dist"

[build.environment]
  NODE_VERSION = "18"

[context.production]
  environment = { NODE_VERSION = "16", NPM_VERSION = "8" }

[context.deploy-preview]
  command = "npm run build:preview"

[context.branch-deploy]
  command = "npm run build:branch"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"

[dev]
  framework = "#custom"
  command = "npm run dev"
  targetPort = 3000
  port = 8888
  publish = "."
  autoLaunch = true

# Enable Deploy Previews
[context.deploy-preview.environment]
  NODE_ENV = "preview"

# Enable Branch Deploys
[context.branch-deploy.environment]
  NODE_ENV = "development"
